CAIMAKE_AUTO_UPDATE := false 

.PHONY: lint
lint:
	cat .gofmt | xargs -I {} gofmt -w -s -d -r {}  $$(find . -name "*.go" -not -path "./vendor/*" -not -path ".git/*")
	gosimple $$(go list ./... | grep -v vendor)
	gometalinter ./... --vendor
 